#!/bin/sh

module=$1
mode="666"

rm -f /dev/$module

/sbin/insmod ./$module.ko $* || exit 1
major=`awk "\\$2==\"$module\" {print \\$1}" /proc/devices`

mknod /dev/$module c $major 0
chmod $mode /dev/$module